---
title: "Project Introduction"
author: "Mark Blackmore"
date: "November 28, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About This Project

This project gives you an opportunity to put into practice all of the skills you have learned by completing the courses in the Microsoft Professional Program for Data Science. It is the culmination of your journey towards becoming a data scientist.

Over the next four weeks, you will need to complete three challenges:

* Explore and analyze data. This accounts for 25% of your grade.
* Create a machine learning model and submit its predictions to a machine learning competition platform. Your competition score accounts for 50% of your grade.
* Write and submit a report of your analysis and findings, and review reports by three of your fellow students. This accounts for 25% of your grade.

In week 4, you must review and grade the reports submitted by three of your fellow students. This will give you an opportunity to reflect on your own report, and learn from your peers.

Note that you cannot submit your report until week 3, but you should start thinking about the kinds of information you want to include as you explore the data. To help you, you can review this sample report, which provides an example of the kind of submission that is expected.

Your report must be submitted by 23:59 on July 21st (UTC) to allow time for peer grading. Note that the deadline shown on the Outline page reflects the final deadline for grading your fellow students' reports, not for submitting your own report.  All other graded work must be submitted before the course ends (as indicated on the Home page), though we recommend that you try to complete your data exploration and submit at least one entry to the competition platform before submitting your report.